### ISSUE TITLE
TypeError: cannot cast ufunc 

### ISSUE THREAD

**Issue by skjerns** [tdedecko/hungarian-algorithm#4]
While just running the script as it is I  get the following results:

```
TypeError: Cannot cast ufunc subtract output from dtype('float64') to dtype('int32') with casting rule 'same_kind'
```

Should only be some dtype setting somewhere, possibly a Python 2 / 3 problem?

update
----
There seems to be a solution as a PR already, but the author is not responding:

https://github.com/tdedecko/hungarian-algorithm/pull/3

**Comment by tdedecko** [comment]
Accepted pull request. This should be resolved.
