### ISSUE TITLE
the meaning of "cost matrix " and "profit_matrix"

### ISSUE THREAD

**Issue by tiankonghenlan20113046** [tdedecko/hungarian-algorithm#7]
Hi, dear author:
In my perspective, the Hungarian algorithm is to find an optimal alignment during a matrix. We can give a cost square matrix and find the positions of the element .But in your script, you give two matrices named cost matrix and profit matrix. what are their meanings?

**Comment by enhuiz** [comment]
> Hi, dear author:
> In my perspective, the Hungarian algorithm is to find an optimal alignment during a matrix. We can give a cost square matrix and find the positions of the element .But in your script, you give two matrices named cost matrix and profit matrix. what are their meanings?

For a profit matrix, you want to find the alignment that maximizes your profit while for a cost matrix, you want to minimize your cost.  

You may refer the following code for the conversion between the two matrices: 

https://github.com/tdedecko/hungarian-algorithm/blob/7c7a1efd52c3fed95d2faa3050a3e5536ce971e9/hungarian.py#L165-L174
